name: Zip Files
'on':
  push: null
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vimtor/action-zip@v1.2
        with:
          files: README.md
          dest: build.zip
      - uses: actions/upload-artifact@v4
        with:
          name: zip file
          path: '${{ github.workspace }}/build.zip'
